config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blogs#index'
  get '/about', to: 'public_view#about'
  get '/contact', to: 'public_view#contact'
  get '/archives/:archive_id/blogs(.:format)', to: 'blogs#index', as: :archive_blogs
  get '/categories/:category_id/blogs(.:format)', to: 'blogs#index', as: :category_blogs

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :blogs

end

app/models/archive.rb
class Archive < ActiveRecord::Base
  has_many :blogs
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :tags
  has_many :categories, through: :tags
  belongs_to :archive

  def tag_list
    return self.categories.map {|category| category.name}.join(",")
  end

  def self.recent_posts
    return Blog.order(:id).last 3
  end


end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tags
  has_many :blogs, through: :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    belongs_to :blog
    belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_layout_variables

  def set_layout_variables
    @categories = Category.all
    @recent_posts = Blog.recent_posts
    @archives = Archive.all
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :set_archive, only: [:show, :edit, :update, :destroy]

  # GET /archives
  # GET /archives.json
  def index
    @archives = Archive.all
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
  end

  # GET /archives/new
  def new
    @archive = Archive.new
  end

  # GET /archives/1/edit
  def edit
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = Archive.new(archive_params)

    respond_to do |format|
      if @archive.save
        format.html { redirect_to @archive, notice: 'Archive was successfully created.' }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1
  # PATCH/PUT /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to @archive, notice: 'Archive was successfully updated.' }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to archives_url, notice: 'Archive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archive_params
      params[:archive]
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    if params[:archive_id]
      @blogs = Archive.find(params[:archive_id]).blogs
    elsif params[:category_id]
      @blogs = Category.find(params[:category_id]).blogs
    else
      @blogs = Blog.all
    end

  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find params[:id]
    # respond_to do |format|
    #   format.html { render 'show' }
    #   format.json { render :json => @blog }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params[:blog]
    end
end

app/controllers/public_view_controller.rb
class PublicViewController < ApplicationController

  def contact

  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/public_view_helper.rb
module PublicViewHelper
end

app/views/archives/_form.html.erb
<%= form_for(@archive) do |f| %>
  <% if @archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% @archive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archives/edit.html.erb
<h1>Editing Archive</h1>

<%= render 'form' %>

<%= link_to 'Show', @archive %> |
<%= link_to 'Back', archives_path %>

app/views/archives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Archives</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archives.each do |archive| %>
      <tr>
        <td><%= link_to 'Show', archive %></td>
        <td><%= link_to 'Edit', edit_archive_path(archive) %></td>
        <td><%= link_to 'Destroy', archive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archive', new_archive_path %>

app/views/archives/new.html.erb
<h1>New Archive</h1>

<%= render 'form' %>

<%= link_to 'Back', archives_path %>

app/views/archives/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_archive_path(@archive) %> |
<%= link_to 'Back', archives_path %>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% @blogs.each do |blog|%>
<article class="post post-<%=blog.id%>">
  <header class="entry-header">
    <h1 class="entry-title">
      <a href="single.html"><%= blog.title %></a>
    </h1>
    <div class="entry-meta">
      <span class="post-category"><a href="#"><%=blog.tag_list%></a></span>

      <span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00"><%= blog.created_at.strftime '%F' %></time></a></span>

      <span class="post-author"><a href="#"><%= blog.owner %></a></span>

    </div>
  </header>
  <div class="entry-content clearfix">
    <p><%= blog.consice %>...</p>
    <div class="read-more cl-effect-14">

      <%= link_to blog_path(blog.id) do %>
          Continue readings
          <span class="meta-nav">→</span>
      <%end%>

    </div>
  </div>
</article>
<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="post post-1">
  <header class="entry-header">
    <h1 class="entry-title"><%= @blog.title %></h1>
    <div class="entry-meta">
      <span class="post-category"><a href="#"><%= @blog.tag_list %></a></span>

      <span class="post-date"><a href="#"><%= @blog.created_at.strftime '%F' %></a></span>

      <span class="post-author"><a href="#"><%= @blog.owner %></a></span>

    </div>
  </header>
  <div class="entry-content clearfix">
    <p><%= @blog.article%></p>
  </div>
</div>

<div class="read-more cl-effect-14">

  <%= link_to blogs_path do %>
      Go Back
      <span class="meta-nav"></span>
  <%end%>

</div>


<!-- begin wwww.htmlcommentbox.com -->
<div id="HCB_comment_box">
  <a href="http://www.htmlcommentbox.com">Comment Form</a> is loading comments...
</div>
<link rel="stylesheet" type="text/css" href="//www.htmlcommentbox.com/static/skins/bootstrap/twitter-bootstrap.css?v=0" />
<script type="text/javascript" id="hcb"> /*<!--*/ if(!window.hcb_user){hcb_user={};} (function(){var s=document.createElement("script"), l=hcb_user.PAGE || (""+window.location).replace(/'/g,"%27"), h="//www.htmlcommentbox.com";s.setAttribute("type","text/javascript");s.setAttribute("src", h+"/jread?page="+encodeURIComponent(l).replace("+","%2B")+"&mod=%241%24wq1rdBcg%24mUGhZuOsW1ZyWmxMt3V%2Ff1"+"&opts=16862&num=10&ts=1442892634095");if (typeof s!="undefined") document.getElementsByTagName("head")[0].appendChild(s);})(); /*-->*/ </script>
<!-- end www.htmlcommentbox.com -->

app/views/layouts/_footer.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p class="copyright">&copy; 2015 Winston</p>
    </div>
  </div>
</div>

app/views/layouts/_header.erb
<div class="row">
  <div class="col-md-4 col-sm-5 col-xs-8">
    <div class="logo">
      <h1><a href="index.html"><b>Programming</b> &amp; Art</a></h1>
    </div>
  </div><!-- col-md-4 -->
  <div class="col-md-8 col-sm-7 col-xs-4">

    <nav class="main-nav" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="glyphicon glyphicon-menu-hamburger"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="cl-effect-11"><a href="/" data-hover="Home">Home</a></li>
          <li class="cl-effect-11"><a href="/about" data-hover="About">About</a></li>
          <li class="cl-effect-11"><a href="/contact" data-hover="Contact">Contact</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
    <!--<div id="header-search-box">-->
      <!--<a id="search-menu" href="#"><span id="search-icon" class="glyphicon glyphicon-search"></span></a>-->
      <!--<div id="search-form" class="search-form">-->
        <!--<form role="search" method="get" id="searchform" action="#">-->
          <!--<input type="search" placeholder="Search" required>-->
          <!--<button type="submit"><span class="ion-ios-search-strong"></span></button>-->
        <!--</form>-->
      <!--</div>-->
    <!--</div>-->
  </div><!-- col-md-8 -->
</div>

app/views/layouts/_main.erb
<article class="post post-1">
    <header class="entry-header">
      <h1 class="entry-title">
        <a href="single.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
      </h1>
      <div class="entry-meta">
        <span class="post-category"><a href="#">Web Design</a></span>

        <span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

        <span class="post-author"><a href="#">Albert Einstein</a></span>

        <span class="comments-link"><a href="#">4 Comments</a></span>
      </div>
    </header>
    <div class="entry-content clearfix">
      <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
      <div class="read-more cl-effect-14">
        <a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
      </div>
    </div>
  </article>

  <article class="post post-2">
    <header class="entry-header">
      <h1 class="entry-title">
        <a href="single.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
      </h1>
      <div class="entry-meta">
        <span class="post-category"><a href="#">Web Design</a></span>

        <span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

        <span class="post-author"><a href="#">Albert Einstein</a></span>

        <span class="comments-link"><a href="#">4 Comments</a></span>
      </div>
    </header>
    <div class="entry-content clearfix">
      <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
      <div class="read-more cl-effect-14">
        <a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
      </div>
    </div>
  </article>

  <article class="post post-3">
    <header class="entry-header">
      <h1 class="entry-title">
        <a href="single.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
      </h1>
      <div class="entry-meta">
        <span class="post-category"><a href="#">Web Design</a></span>

        <span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

        <span class="post-author"><a href="#">Albert Einstein</a></span>

        <span class="comments-link"><a href="#">4 Comments</a></span>
      </div>
    </header>
    <div class="entry-content clearfix">
      <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
      <div class="read-more cl-effect-14">
        <a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
      </div>
    </div>
  </article>

  <article class="post post-4">
    <header class="entry-header">
      <h1 class="entry-title">
        <a href="single.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
      </h1>
      <div class="entry-meta">
        <span class="post-category"><a href="#">Web Design</a></span>

        <span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

        <span class="post-author"><a href="#">Albert Einstein</a></span>

        <span class="comments-link"><a href="#">4 Comments</a></span>
      </div>
    </header>
    <div class="entry-content clearfix">
      <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
      <div class="read-more cl-effect-14">
        <a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
      </div>
    </div>
  </article>

app/views/layouts/_side_bar.erb
  <div class="widget widget-recent-posts">
    <h3 class="widget-title">Recent Posts</h3>
    <ul>
      <% @recent_posts.each do |post|%>
      <li>
        <%= link_to post.title, blog_path(post.id) %>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="widget widget-archives">
    <h3 class="widget-title">Archives</h3>
    <ul>
      <% @archives.each do |archive| %>
          <li>
            <%= link_to archive.name,  archive_blogs_path(archive.id) %>
          </li>
      <% end %>

    </ul>
  </div>

  <div class="widget widget-category">
    <h3 class="widget-title">Category</h3>
    <ul>
      <% @categories.each do |category| %>
          <li>
            <%= link_to category.name,  category_blogs_path(category.id) %>
          </li>
      <% end %>
    </ul>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Winston's Appraoch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= render 'layouts/header' %>
</div>

<div class="content-body">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
      <div class="col-md-3">
        <%= render 'layouts/side_bar'%>
      </div>
    </div>
  </div>
</div>

<div id="site-footer">
    <%= render 'layouts/footer' %>
</div>



</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>